apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: doggybeans
  name: spring-doggy-beans
spec:
  replicas: 5
  selector:
    matchLabels:
      app: doggybeans
  strategy: {}
  template:
    metadata:
      labels:
        app: doggybeans
    spec:
      containers:
        - image: v1:latest
          name: doggybeans
          resources: {}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: doggybeans-service
spec:
  selector:
    app: doggybeans
  ports:
    - port: 9080
      targetPort: 8080
  type: LoadBalancer
