apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: doggybeans
  name: doggybeans

spec:
  replicas: 7
  selector:
    matchLabels:
      app: doggybeans
  template:
    metadata:
      labels:
        app: doggybeans
        actorSystemName: doggybeans
    spec:
      containers:
        - name: doggybeans
          image: sidutti/first:latest
          ports:
            # akka remoting
            - name: remoting
              containerPort: 2552
              protocol: TCP
            # akka-management and bootstrap
            - name: management
              containerPort: 8558
              protocol: TCP
            - name: akkahttp
              containerPort: 8081
              protocol: TCP
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: "/ready"
              port: management
            periodSeconds: 100
            failureThreshold: 30
            initialDelaySeconds: 100
          livenessProbe:
            httpGet:
              path: "/alive"
              port: management
            periodSeconds: 100
            failureThreshold: 50
            initialDelaySeconds: 20
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: REQUIRED_CONTACT_POINT_NR
              value: "2"
            - name: MONGODB_HOST
              value: mongo-service
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
rules:
  - apiGroups: [ "" ] # "" indicates the core API group
    resources: [ "pods" ]
    verbs: [ "get", "watch", "list" ]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
  namespace: default
subjects:
  # Note the `name` line below. The first default refers to the namespace. The second refers to the service account name.
  # For instance, `name: system:serviceaccount:myns:default` would refer to the default service account in namespace `myns`
  - kind: User
    name: system:serviceaccount
  - kind: Group
    name: system:serviceaccount
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: doggybeans-service

spec:
  selector:
    app: doggybeans
    tier: backend
  ports:
    - port: 9080
      targetPort: 8080
      name: http
    - port: 9081
      targetPort: 8081
      name: akkahttp
  type: LoadBalancer