apiVersion: v1
kind: Service
metadata:
  name: mongo-node-1
  labels:
    name: mongo-node-1
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongo-node-1
  selector:
    name: mongo-node-1
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-node-1-rc
  labels:
    name: mongo-node-1-rc
spec:
  replicas: 1
  selector:
    name: mongo-node-1
  template:
    metadata:
      labels:
        name: mongo-node-1
    spec:
      containers:
        - name: mongo-node-1
          image: mongo:4.2
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--bind_ip_all"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-node-1-db
              mountPath: /data/db/mongo/node1
      volumes:
        - name: mongo-node-1-db
          persistentVolumeClaim:
            claimName: mongo-node-1-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-node-2
  labels:
    name: mongo-node-2
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongo-node-2
  selector:
    name: mongo-node-2

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-node-2-rc
  labels:
    name: mongo-node-2-rc
spec:
  replicas: 1
  selector:
    name: mongo-node-2
  template:
    metadata:
      labels:
        name: mongo-node-2
    spec:
      containers:
        - name: mongo-node-2
          image: mongo:4.2
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--bind_ip_all"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-node-2-db
              mountPath: /data/db/mongo/node2
      volumes:
        - name: mongo-node-2-db
          persistentVolumeClaim:
            claimName: mongo-node-2-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-node-3
  labels:
    name: mongo-node-3
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongo-node-3
  selector:
    name: mongo-node-3
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-node-3-rc
  labels:
    name: mongo-node-3-rc
spec:
  replicas: 1
  selector:
    name: mongo-node-3
  template:
    metadata:
      labels:
        name: mongo-node-3
    spec:
      containers:
        - name: mongo-node-3
          image: mongo:4.2
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--bind_ip_all"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-node-3-db
              mountPath: /data/db/
      volumes:
        - name: mongo-node-3-db
          persistentVolumeClaim:
            claimName: mongo-node-3-pvc