apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: doggybeans-1
  labels:
    name: mongo-service
    component: backend
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo
    component: backend