apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-node-1-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: sidutti2
    path: "/mnt/ntfs/mongo/node1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-node-2-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: sidutti2
    path: "/mnt/ntfs/mongo/node2"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-node-3-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: sidutti2
    path: "/mnt/ntfs/mongo/node3"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-node-1-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-node-2-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-node-3-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi