---
apiVersion: v1
kind: Service
metadata:
  name: doggybeans-service
spec:
  selector:
    app: doggybeans
    tier: backend
  ports:
    - port: 9080
      targetPort: 8080
      name: http
    - port: 9081
      targetPort: 8081
      name: akkahttp
    - port: 8558
      targetPort: 8558
      name: akkamanagement
  type: NodePort