/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.harish.sidutti.java-conventions")
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-data-elasticsearch:2.7.0")
    implementation("org.slf4j:slf4j-api:1.7.36")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.13.3")
    testImplementation("org.slf4j:slf4j-simple:1.7.36")
    testImplementation("junit:junit:4.13.2")
    testImplementation("com.squareup.okhttp3:mockwebserver:4.9.3")
    testImplementation("com.google.guava:guava:31.1-jre")
    testImplementation("org.yaml:snakeyaml:1.26")
}

description = "sidfinance"
