spring:
  application:
    name: doggybeanselastic
  elasticsearch:
    uris: 127.0.0.1:9200
    username: elastic
    password: Abraca
management:
  endpoints:
    web:
      exposure:
        include: '*'

app:
  service:
    name: http://localhost:8080